import { expect, test, type Page } from '@playwright/test'

async function selectTflStation(page: Page, name: string) {
  await page.getByRole('searchbox').fill(name)
  await page.getByRole('option').filter({ has: page.getByText(name, { exact: true }) }).filter({ hasText: /\d+ lines/ }).click()
}
async function open(page: Page) {
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
}

test('Stratford joins its aliases, keeps TfL on rail failure and seeks the selected rail service', async ({ page }) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/all-change-national-rail-network-liverpool-street.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await open(page)
  expect(requests.some(url => url.includes('LondonCombinedStationBoard'))).toBe(false)
  await selectTflStation(page, 'Stratford')
  const board = page.getByRole('region', { name: 'Stratford timetable', exact: true })
  const combined = page.locator('.london-combined-board')
  await expect(combined).toContainText('some National Rail services unavailable')
  await expect(board.locator('tbody tr:has(button)')).toHaveCount(4)
  const filter = board.getByRole('combobox', { name: 'Stratford board line' })
  await expect(filter.locator('option')).toHaveText(['All lines', 'Central', 'DLR', 'Elizabeth line', 'Jubilee', 'Mildmay'])
  await page.unroute('**/all-change-national-rail-network-liverpool-street.json')
  await combined.getByRole('button', { name: 'Retry National Rail board' }).click()
  await expect(filter.locator('option')).toHaveText(['All lines', 'Central', 'DLR', 'Elizabeth line', 'Greater Anglia', 'Jubilee', 'Mildmay'])
  await filter.selectOption('Greater Anglia')
  await expect(board.locator('tbody tr:has(button)')).toHaveCount(4)
  await board.locator('tbody tr button').first().click()
  const service = await page.locator('.london-experience').getAttribute('data-selected-rail-service')
  expect(service).toMatch(/^national-rail:WTT:/)
  const selection = board.locator('.london-station-board-selection')
  const selectedTime = (await selection.textContent())!.match(/\d{2}:\d{2}/)![0]
  await expect(page.locator('.london-national-rail-board')).toHaveCount(0)
  expect(await combined.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  const boardBounds = await board.boundingBox(), cardBounds = await page.locator('.has-station-board').boundingBox()
  expect(boardBounds!.width).toBeGreaterThan(cardBounds!.width * .8)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await board.scrollIntoViewIfNeeded()
  await board.getByRole('button', { name: 'Show movement', exact: true }).click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-selected-rail-service', service!)
  await expect(page.getByRole('button', { name: 'Hide National Rail', exact: true, includeHidden: true })).toBeAttached()
  await expect(page.locator('.london-transport input[type="range"]')).toHaveValue(String(Number(selectedTime.slice(0, 2)) * 3600 + Number(selectedTime.slice(3)) * 60))
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('the rail entry offers the same Stratford board and sends a TfL service to its renderer', async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await open(page)
  await page.getByRole('searchbox').fill('SRA')
  await page.getByRole('option').filter({ hasText: 'NATIONAL RAIL · SRA' }).click()
  const card = page.getByRole('region', { name: 'National Rail at Stratford', exact: true })
  if (info.project.name === 'iphone-webkit') await card.locator(':scope > details > summary').click()
  await card.getByRole('combobox', { name: 'National Rail station' }).selectOption('liverpool-street')
  const liverpool = page.getByRole('region', { name: 'National Rail at Liverpool Street', exact: true })
  await expect(liverpool.getByRole('combobox', { name: 'Liverpool Street board line' }).locator('option')).toHaveText(['All lines', 'Central', 'Circle', 'Elizabeth line', 'Greater Anglia', 'Hammersmith & City', 'Metropolitan', 'Weaver'])
  await liverpool.getByRole('combobox', { name: 'National Rail station' }).selectOption('stratford')
  const board = card.getByRole('region', { name: 'Stratford timetable', exact: true })
  const filter = board.getByRole('combobox', { name: 'Stratford board line' })
  await expect(filter.locator('option')).toContainText(['All lines', 'Central', 'DLR', 'Elizabeth line', 'Greater Anglia', 'Jubilee', 'Mildmay'])
  await filter.selectOption('Central')
  await board.getByRole('button', { name: 'Arrivals', exact: true }).click()
  await board.locator('tbody tr button').first().click()
  const service = await page.locator('.london-experience').getAttribute('data-selected-tfl-service')
  expect(service).toMatch(/^central:/)
  await expect(board.locator('.ms-flap__face').first()).toHaveCSS('animation-name', 'none')
  await board.getByRole('button', { name: 'Show movement', exact: true }).click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-selected-tfl-service', service!)
  await expect(card).toHaveAttribute('data-hero-dismissed', 'true')
  await expect(page.locator('.has-station-board')).toHaveCount(0)
})
