import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('cycle day loads on demand, shares the clock, and exposes dismissible dock profiles', async ({ page }, info) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  expect(requests.some(url => /cycle-day|LondonCycleStudy/.test(url))).toBe(false)
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  await expect(page.getByRole('heading', { name: 'London by cycle' })).toBeVisible()
  await expect(page.getByRole('img', { name: /recorded hires in progress/ })).toBeVisible()
  const clock = page.getByRole('slider', { name: 'Cycle time of day' })
  await expect(clock).toHaveValue('27900')
  await expect(page.locator('.cycle-header')).toContainText('Friday 29 May 2026')
  await page.getByRole('button', { name: '17:30 evening' }).click()
  await expect(clock).toHaveValue('63000')
  await page.screenshot({ path: `/tmp/allchange-cycle/${info.project.name}-overview.png` })
  const search = page.getByRole('combobox', { name: 'Find a docking station' })
  await search.fill('Tooley')
  await search.press('ArrowDown')
  await search.press('Enter')
  const card = page.getByRole('complementary', { name: /Cycle hire at Tooley/ })
  await expect(card).toContainText('Departures')
  await expect(card).toContainText('net returns this interval')
  await expect(card.getByRole('img', { name: 'Daily departures and returns profile' })).toBeVisible()
  await card.getByRole('button', { name: /^Close/ }).click()
  await expect(card.getByRole('img')).toBeHidden()
  await page.getByRole('button', { name: 'Zoom in on cycle map' }).click()
  await page.screenshot({ path: `/tmp/allchange-cycle/${info.project.name}-dock.png` })
  await card.getByRole('button', { name: /^Show/ }).click()
  await expect(card.getByRole('heading')).toContainText('Tooley')
  await page.getByRole('button', { name: '08:30 morning' }).click()
  await expect(clock).toHaveValue('30600')
  await page.getByRole('button', { name: 'Resume cycle motion' }).click()
  await expect(clock).not.toHaveValue('30600')
  await page.getByRole('button', { name: 'Pause cycle motion' }).click()
  await clock.fill('86400')
  await expect(card).toContainText('End of day · no interval')
  await page.getByRole('button', { name: '17:30 evening' }).click()
  await page.getByRole('button', { name: 'Back to rail' }).click()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await expect(page.locator('.london-transport input[type="range"]')).toHaveValue('63000')
  expect(requests.filter(url => url.endsWith('all-change-cycle-day.json'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('cycle data retries and reduced motion keeps controls keyboard accessible', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/all-change-cycle-day.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  await expect(page.getByRole('status')).toContainText('Cycle study unavailable')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toBeDisabled()
  await page.unroute('**/all-change-cycle-day.json')
  await page.getByRole('button', { name: 'Retry cycle study' }).click()
  await expect(page.locator('.cycle-map canvas')).toBeVisible()
  await expect(page.locator('.cycle-study')).toHaveAttribute('data-reduced-motion', 'true')
  const morning = page.getByRole('button', { name: '08:30 morning' })
  await morning.focus()
  await morning.press('Space')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('30600')
  await expect(page.getByRole('button', { name: 'Resume cycle motion' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Find a docking station' }).fill('not-a-real-dock')
  await expect(page.getByRole('listbox')).toContainText('No matching dock')
})
