import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('guided patterns open audited four-day profiles without fetching every journey day', async ({ page }, info) => {
  const requests: string[] = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  const patterns = page.getByRole('combobox', { name: 'Explore a cycle pattern' })
  await expect(patterns).toBeEnabled()
  expect(requests.some(url => /\/profiles\/|LondonCycleComparison/.test(url))).toBe(false)
  await patterns.selectOption('1072')
  const card = page.getByRole('complementary', { name: 'Cycle hire at Waterloo Station 3, Waterloo', exact: true })
  const comparison = page.getByRole('region', { name: 'Four-day dock comparison' })
  await expect(comparison).toContainText('205 departures and 2 returns')
  await expect(comparison.getByRole('button', { name: 'Thursday 28 May', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('30600')
  await expect(page.getByRole('button', { name: 'Resume cycle motion' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Zoom out on cycle map' })).toBeEnabled()
  expect(requests.filter(url => url.includes('/all-change-cycle/days/'))).toHaveLength(2)
  expect(requests.filter(url => url.includes('/all-change-cycle/profiles/'))).toHaveLength(1)
  const friday = comparison.getByRole('button', { name: 'Friday 29 May', exact: true })
  await friday.click()
  await expect(friday).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('30600')
  await card.getByRole('button', { name: /^Close/ }).click()
  await expect(comparison).toHaveCount(0)
  await card.getByRole('button', { name: /^Show/ }).click()
  await expect(friday).toBeVisible()
  expect(requests.filter(url => url.endsWith('/profiles/1072.json'))).toHaveLength(1)
  await patterns.selectOption('999')
  await expect(comparison).toContainText('137 returns and 12 departures')
  await patterns.selectOption('1075')
  await expect(comparison).toContainText('272 on Sunday')
  await expect(comparison.getByRole('button', { name: 'Sunday 31 May', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('50400')
  await page.locator('.cycle-card').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: `/tmp/allchange-cycle/${info.project.name}-guided-comparison.png` })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await comparison.getByText('Why this example?', { exact: true }).click()
  await expect(comparison.locator('.cycle-guide-copy')).toBeVisible()
  await page.getByRole('button', { name: 'Back to selected day' }).click()
  await expect(page.getByRole('img', { name: 'Daily departures and returns profile' })).toBeVisible()
})

test('dock comparison retries, ignores stale docks and retains unavailable dates', async ({ page }) => {
  let release!: () => void
  const held = new Promise<void>(resolve => { release = resolve })
  await page.route('**/all-change-cycle/profiles/1072.json', async route => { await held; await route.continue() })
  await page.route('**/all-change-cycle/profiles/999.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.route('**/all-change-cycle/days/2026-05-28.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  const patterns = page.getByRole('combobox', { name: 'Explore a cycle pattern' })
  await expect(patterns).toBeEnabled()
  const started = page.waitForRequest('**/all-change-cycle/profiles/1072.json')
  await patterns.selectOption('1072')
  await expect(page.getByRole('status')).toContainText('Cycle study unavailable')
  const day = page.getByRole('combobox', { name: 'Cycle study day' })
  await expect(day).toBeVisible()
  await day.selectOption('2026-05-29')
  await started
  await page.unroute('**/all-change-cycle/days/2026-05-28.json')
  await patterns.selectOption('999')
  const comparison = page.getByRole('region', { name: 'Four-day dock comparison' })
  await expect(comparison).toContainText('Comparison unavailable')
  const delivered = page.waitForResponse('**/all-change-cycle/profiles/1072.json')
  release()
  await delivered
  await expect(comparison).toContainText('Comparison unavailable')
  await page.unroute('**/all-change-cycle/profiles/999.json')
  await page.getByRole('button', { name: 'Retry dock comparison' }).click()
  await expect(comparison.getByRole('button', { name: 'Thursday 28 May', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to selected day' }).click()
  await page.getByRole('combobox', { name: 'Find a docking station' }).fill('Pindar Street')
  await page.getByRole('option', { name: 'Pindar Street, Liverpool Street', exact: true }).click()
  await page.getByRole('button', { name: 'Compare four days', exact: true }).click()
  const saturday = comparison.getByRole('button', { name: 'Saturday 30 May', exact: true })
  await expect(saturday).toContainText('No included records · unavailable')
  await saturday.click()
  await expect(saturday).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Back to selected day' }).click()
  await expect(page.locator('.cycle-counts strong')).toHaveText(['—', '—'])
})

test('weekday/weekend switching preserves dock identity, time, zoom and comparison scales', async ({ page }, info) => {
  const files: string[] = []
  page.on('request', request => { if (request.url().includes('/all-change-cycle/')) files.push(request.url()) })
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  const search = page.getByRole('combobox', { name: 'Find a docking station' })
  await expect(search).toBeEnabled()
  await page.getByRole('button', { name: '08:30 morning' }).click()
  await search.fill('Pindar Street')
  await page.getByRole('option', { name: 'Pindar Street, Liverpool Street', exact: true }).click()
  const card = page.getByRole('complementary', { name: 'Cycle hire at Pindar Street, Liverpool Street', exact: true })
  const scale = await card.locator('.cycle-profile-scale').textContent()
  const date = page.getByRole('combobox', { name: 'Cycle study day' })
  await page.getByRole('button', { name: 'Zoom in on cycle map' }).click()
  await date.selectOption('2026-05-28')
  await expect(card.locator('.cycle-profile-scale')).toHaveText(scale!)
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('30600')
  await date.selectOption('2026-05-30')
  await expect(card).toContainText('No included records for this dock on this date')
  await expect(card.getByRole('img')).toHaveCount(0)
  await expect(card.locator('.cycle-counts strong')).toHaveText(['—', '—'])
  await date.selectOption('2026-05-31')
  await expect(card.locator('.cycle-profile-scale')).toHaveText(scale!)
  await expect(page.getByRole('button', { name: 'Zoom out on cycle map' })).toBeEnabled()
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('30600')
  await card.getByRole('button', { name: /^Close/ }).click()
  await page.screenshot({ path: `/tmp/allchange-cycle/${info.project.name}-weekend.png` })
  await date.selectOption('2026-05-29')
  await expect(card.getByRole('button', { name: /^Show/ })).toBeVisible()
  expect(files.filter(url => url.endsWith('manifest.json'))).toHaveLength(1)
  expect(files.filter(url => url.includes('/days/'))).toHaveLength(4)
})

test('late day downloads cannot replace a newer selection and comparison failures retry', async ({ page }) => {
  let release!: () => void
  const held = new Promise<void>(resolve => { release = resolve })
  await page.route('**/all-change-cycle/days/2026-05-30.json', async route => { await held; await route.continue() })
  await page.route('**/all-change-cycle/days/2026-05-31.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  await expect(page.locator('.cycle-map canvas')).toBeVisible()
  await page.getByRole('button', { name: '17:30 evening' }).click()
  const date = page.getByRole('combobox', { name: 'Cycle study day' })
  await date.selectOption('2026-05-30')
  await expect(page.getByRole('status')).toContainText(/Saturday,? 30 May 2026: Loading/)
  await expect(page.locator('.cycle-card')).toHaveCount(0)
  await date.selectOption('2026-05-31')
  await expect(page.getByRole('status')).toContainText(/Sunday,? 31 May 2026: Cycle study unavailable/)
  const delivered = page.waitForResponse(response => response.url().endsWith('2026-05-30.json'))
  release()
  await delivered
  await expect(page.getByRole('status')).toContainText(/Sunday,? 31 May 2026: Cycle study unavailable/)
  await page.unroute('**/all-change-cycle/days/2026-05-31.json')
  await page.getByRole('button', { name: 'Retry cycle study' }).click()
  await expect(page.locator('.cycle-map canvas')).toBeVisible()
  await expect(date).toHaveValue('2026-05-31')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('63000')
})

test('cycle day loads on demand, shares the clock, and exposes dismissible dock profiles', async ({ page }, info) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  expect(requests.some(url => /all-change-cycle|LondonCycleStudy/.test(url))).toBe(false)
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  await expect(page.getByRole('heading', { name: 'London by cycle' })).toBeVisible()
  await expect(page.getByRole('img', { name: /recorded hires in progress/ })).toBeVisible()
  const clock = page.getByRole('slider', { name: 'Cycle time of day' })
  await expect(clock).toHaveValue('27900')
  await expect(page.getByRole('combobox', { name: 'Cycle study day' })).toHaveValue('2026-05-29')
  await page.getByRole('button', { name: '17:30 evening' }).click()
  await expect(clock).toHaveValue('63000')
  await page.screenshot({ path: `/tmp/allchange-cycle/${info.project.name}-overview.png` })
  const search = page.getByRole('combobox', { name: 'Find a docking station' })
  await search.fill('Tooley')
  await search.press('ArrowDown')
  await search.press('Enter')
  const card = page.getByRole('complementary', { name: /Cycle hire at Tooley/ })
  await expect(card).toContainText('Departures')
  await expect(card).toContainText('net returns this interval')
  await expect(card.getByRole('img', { name: 'Daily departures and returns profile' })).toBeVisible()
  await card.getByRole('button', { name: /^Close/ }).click()
  await expect(card.getByRole('img')).toBeHidden()
  await page.getByRole('button', { name: 'Zoom in on cycle map' }).click()
  await page.screenshot({ path: `/tmp/allchange-cycle/${info.project.name}-dock.png` })
  await card.getByRole('button', { name: /^Show/ }).click()
  await expect(card.getByRole('heading')).toContainText('Tooley')
  await page.getByRole('button', { name: '08:30 morning' }).click()
  await expect(clock).toHaveValue('30600')
  await page.getByRole('button', { name: 'Resume cycle motion' }).click()
  await expect(clock).not.toHaveValue('30600')
  await page.getByRole('button', { name: 'Pause cycle motion' }).click()
  await clock.fill('86400')
  await expect(card).toContainText('End of day · no interval')
  await page.getByRole('button', { name: '17:30 evening' }).click()
  await page.getByRole('button', { name: 'Back to rail' }).click()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await expect(page.locator('.london-transport input[type="range"]')).toHaveValue('63000')
  expect(requests.filter(url => url.endsWith('all-change-cycle/days/2026-05-29.json'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('cycle data retries and reduced motion keeps controls keyboard accessible', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/all-change-cycle/days/2026-05-29.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  await expect(page.getByRole('status')).toContainText('Cycle study unavailable')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toBeDisabled()
  await page.unroute('**/all-change-cycle/days/2026-05-29.json')
  await page.getByRole('button', { name: 'Retry cycle study' }).click()
  await expect(page.locator('.cycle-map canvas')).toBeVisible()
  await expect(page.locator('.cycle-study')).toHaveAttribute('data-reduced-motion', 'true')
  const morning = page.getByRole('button', { name: '08:30 morning' })
  await morning.focus()
  await morning.press('Space')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('30600')
  await expect(page.getByRole('button', { name: 'Resume cycle motion' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Find a docking station' }).fill('not-a-real-dock')
  await expect(page.getByRole('listbox')).toContainText('No matching dock')
})
