import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('guided cycle comparison opens lazily and switches days without losing its clock', async ({ page }) => {
  const requests: string[] = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  const patterns = page.getByRole('combobox', { name: 'Explore a cycle pattern' })
  await expect(patterns).toBeEnabled()
  expect(requests.some(url => /\/profiles\/|LondonCycleComparison/.test(url))).toBe(false)
  await patterns.selectOption('1072')
  const card = page.getByRole('complementary', { name: 'Cycle hire at Waterloo Station 3, Waterloo', exact: true })
  const comparison = page.getByRole('region', { name: 'Four-day dock comparison' })
  await expect(comparison).toContainText('205 departures and 2 returns')
  await expect(comparison.getByRole('button', { name: 'Thursday 28 May', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('30600')
  await expect(page.getByRole('button', { name: 'Resume cycle motion' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Zoom out on cycle map' })).toBeEnabled()
  expect(requests.filter(url => url.includes('/all-change-cycle/days/'))).toHaveLength(2)
  expect(requests.filter(url => url.includes('/all-change-cycle/profiles/'))).toHaveLength(1)
  const friday = comparison.getByRole('button', { name: 'Friday 29 May', exact: true })
  await friday.click()
  await expect(friday).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('slider', { name: 'Cycle time of day' })).toHaveValue('30600')
  await card.getByRole('button', { name: /^Close/ }).click()
  await expect(comparison).toHaveCount(0)
  await card.getByRole('button', { name: /^Show/ }).click()
  await expect(friday).toBeVisible()
  expect(requests.filter(url => url.endsWith('/profiles/1072.json'))).toHaveLength(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await comparison.getByText('Why this example?', { exact: true }).click()
  await expect(comparison.locator('.cycle-guide-copy')).toBeVisible()
  await page.getByRole('button', { name: 'Back to selected day' }).click()
  await expect(page.getByRole('img', { name: 'Daily departures and returns profile' })).toBeVisible()
})

test('cycle day loads on demand, shares the clock, and exposes dismissible dock profiles', async ({ page }) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  expect(requests.some(url => /all-change-cycle|LondonCycleStudy/.test(url))).toBe(false)
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Explore cycle-hire day' }).click()
  await expect(page.getByRole('heading', { name: 'London by cycle' })).toBeVisible()
  await expect(page.getByRole('img', { name: /recorded hires in progress/ })).toBeVisible()
  const clock = page.getByRole('slider', { name: 'Cycle time of day' })
  await expect(clock).toHaveValue('27900')
  await expect(page.getByRole('combobox', { name: 'Cycle study day' })).toHaveValue('2026-05-29')
  await page.getByRole('button', { name: '17:30 evening' }).click()
  await expect(clock).toHaveValue('63000')
  const search = page.getByRole('combobox', { name: 'Find a docking station' })
  await search.fill('Tooley')
  await search.press('ArrowDown')
  await search.press('Enter')
  const card = page.getByRole('complementary', { name: /Cycle hire at Tooley/ })
  await expect(card).toContainText('Departures')
  await expect(card).toContainText('net returns this interval')
  await expect(card.getByRole('img', { name: 'Daily departures and returns profile' })).toBeVisible()
  await card.getByRole('button', { name: /^Close/ }).click()
  await expect(card.getByRole('img')).toBeHidden()
  await page.getByRole('button', { name: 'Zoom in on cycle map' }).click()
  await card.getByRole('button', { name: /^Show/ }).click()
  await expect(card.getByRole('heading')).toContainText('Tooley')
  await page.getByRole('button', { name: '08:30 morning' }).click()
  await expect(clock).toHaveValue('30600')
  await page.getByRole('button', { name: 'Resume cycle motion' }).click()
  await expect(clock).not.toHaveValue('30600')
  await page.getByRole('button', { name: 'Pause cycle motion' }).click()
  await clock.fill('86400')
  await expect(card).toContainText('End of day · no interval')
  await page.getByRole('button', { name: '17:30 evening' }).click()
  await page.getByRole('button', { name: 'Back to rail' }).click()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await expect(page.locator('.london-transport input[type="range"]')).toHaveValue('63000')
  expect(requests.filter(url => url.endsWith('all-change-cycle/days/2026-05-29.json'))).toHaveLength(1)
  expect(errors).toEqual([])
})
