import { expect, test } from '@playwright/test'

test('Eurostar has a separate dated board, independent retry, and honest movement availability', async ({ page }, info) => {
  const errors: string[] = [], requests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => requests.push(request.url()))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/all-change-national-rail-network-eurostar.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  expect(requests.some(url => /eurostar|LondonCombinedStationBoard/.test(url))).toBe(false)
  const clock = page.locator('.london-transport input[type="range"]')
  await clock.fill('27900')
  await page.getByRole('searchbox').fill("King's Cross St. Pancras")
  await page.getByRole('option').filter({ has: page.getByText("King's Cross St. Pancras", { exact: true }) }).filter({ hasText: /\d+ lines/ }).click()
  const area = page.getByRole('combobox', { name: 'Rail station area', exact: true })
  await area.selectOption('eurostar')
  const combined = page.locator('.london-combined-board')
  const board = page.getByRole('region', { name: 'St Pancras Eurostar timetable', exact: true })
  await expect(combined).toContainText('some Eurostar services unavailable')
  await expect(board.locator('tbody tr:has(button)')).toHaveCount(4) // TfL survives the failed Eurostar download.
  await page.unroute('**/all-change-national-rail-network-eurostar.json')
  await combined.getByRole('button', { name: 'Retry Eurostar board' }).click()
  await expect(combined).toContainText('40 of 55 Eurostar services have London movement')
  await expect(combined).toContainText('Departure times are not boarding or check-in deadlines')
  await combined.locator('details > summary').click()
  await expect(combined.getByRole('link', { name: 'Eurostar arrival guidance' })).toHaveAttribute('href', 'https://www.eurostar.com/travel-info/your-trip/check-in')
  await combined.locator('details > summary').click()
  const line = board.getByRole('combobox', { name: 'St Pancras Eurostar board line' })
  await expect(line.locator('option')).toContainText(['Eurostar'])
  await expect(line.locator('option').filter({ hasText: /Southeastern|Midlands|Thameslink/ })).toHaveCount(0)
  await line.selectOption('Eurostar')
  await clock.fill('25440')
  await board.locator('tbody tr button').first().click()
  const selection = board.locator('.london-station-board-selection')
  await expect(selection).toContainText('Eurostar 9004 · 07:04')
  await expect(selection).toContainText('Paris-Nord')
  await expect(selection).toContainText('Timetable only')
  await expect(selection.getByRole('button', { name: 'Show movement' })).toHaveCount(0)
  await page.getByRole('button', { name: "Close King's Cross St. Pancras card", exact: true }).click()
  await page.getByRole('button', { name: "Show King's Cross St. Pancras card", exact: true }).click()
  await expect(area).toHaveValue('eurostar')
  await clock.fill('27900')
  await board.locator('tbody tr button').first().click()
  await expect(selection).toContainText('Eurostar 9008 · 08:01')
  await expect(selection.getByRole('button', { name: 'Show movement' })).toBeVisible()
  await board.getByRole('button', { name: 'Arrivals', exact: true }).click()
  await expect(selection).toHaveCount(0)
  await board.locator('tbody tr button').first().click()
  await expect(selection).toContainText('From Paris-Nord')
  await expect(selection).toContainText('Eurostar 9007 · 08:30')
  await area.scrollIntoViewIfNeeded()
  expect((await area.boundingBox())!.height).toBeGreaterThanOrEqual(44)
  expect(await combined.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await board.scrollIntoViewIfNeeded()
  await page.screenshot({ path: `/tmp/allchange-eurostar/${info.project.name}.png`, animations: 'disabled' })
  await selection.getByRole('button', { name: 'Show movement', exact: true }).click()
  await expect(clock).toHaveValue('30600')
  await expect(page.locator('.london-experience')).toHaveAttribute('data-selected-rail-service', 'eurostar:9007-0904:2026-09-04')
  await expect(page.locator('.london-experience')).toHaveAttribute('data-spatial-layout', 'geographic')
  await expect(page.getByRole('region', { name: 'National Rail at St Pancras Eurostar', exact: true })).toHaveAttribute('data-hero-dismissed', 'true')
  expect(errors).toEqual([])
})

test('the UIC station entry opens Eurostar directly and respects the end of the day', async ({ page }, info) => {
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await page.getByRole('searchbox').fill('7015400')
  await page.getByRole('option').filter({ hasText: 'NATIONAL RAIL · 7015400' }).click()
  const card = page.getByRole('region', { name: 'National Rail at St Pancras Eurostar', exact: true })
  if (info.project.name === 'iphone-webkit' && await card.locator(':scope > details').getAttribute('open') === null) await card.locator(':scope > details > summary').click()
  await expect(card).toContainText('40 of 55')
  await expect(card.getByRole('combobox', { name: 'Rail station area', exact: true })).toHaveCount(0)
  await card.getByRole('combobox', { name: 'St Pancras Eurostar board line' }).selectOption('Eurostar')
  await card.locator('tbody tr button').first().click()
  await expect(card.locator('.london-station-board-selection')).toContainText('Eurostar 9008 · 08:01')
  await page.getByRole('searchbox').fill('9008')
  await page.getByRole('option').filter({ hasText: 'Eurostar 9008' }).click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-selected-rail-service', 'eurostar:9008-0904:2026-09-04')
  await expect(card).toBeVisible()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-study-window', 'day')
  await page.locator('.london-transport input[type="range"]').fill('86400')
  await expect(card).toContainText('Outside study window')
  await expect(card.locator('tbody tr:has(button)')).toHaveCount(0)
})
