import { expect, test } from '@playwright/test'

test('station and pulse cards dismiss without clearing selection, and reopen on demand', async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  const search = page.getByRole('searchbox')
  await search.fill('Bank')
  await page.getByRole('option', { name: /Bank/ }).first().click()
  const demand = page.getByRole('region', { name: 'Typical passenger demand' })
  await expect(demand).toContainText('Bank and Monument')
  await demand.getByRole('button', { name: /Changing/ }).click()
  const close = page.getByRole('button', { name: 'Close Bank card', exact: true })
  const bounds = await close.boundingBox()
  expect(bounds!.width).toBeGreaterThanOrEqual(44)
  expect(bounds!.height).toBeGreaterThanOrEqual(44)
  await close.focus()
  await close.press('Enter')
  await expect(demand).not.toBeVisible()
  await expect(page.getByRole('region', { name: 'Bank timetable', exact: true })).not.toBeVisible()
  await expect(search).toHaveValue('Bank')
  await expect(search).toBeVisible()
  await expect(page.getByRole('region', { name: 'Playback controls' })).toBeVisible()
  await expect(page.locator('.london-experience')).toHaveClass(/has-selection/)
  const reopen = page.getByRole('button', { name: 'Show Bank card', exact: true })
  await expect(reopen).toBeFocused()
  expect((await page.locator('.london-status-card').boundingBox())!.height).toBeLessThan(64)
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  await page.screenshot({ path: `/tmp/allchange-hero-dismiss/${info.project.name}-closed.png` })
  await reopen.click()
  await expect(demand.getByRole('button', { name: /Changing/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  await page.screenshot({ path: `/tmp/allchange-hero-dismiss/${info.project.name}-open.png` })
  await page.getByRole('button', { name: 'Open Bank pulse', exact: true }).click()
  await page.getByRole('button', { name: 'Close Bank card', exact: true }).click()
  await expect(page.locator('.london-experience')).toHaveClass(/is-pulse-study/)
  await page.getByRole('button', { name: 'Show Bank card', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue('bank')
  await page.getByRole('button', { name: 'Close Bank card', exact: true }).click()
  await search.fill('Whitechapel')
  await page.getByRole('option', { name: /Whitechapel/ }).first().click()
  await expect(page.getByRole('region', { name: 'Whitechapel timetable', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close Whitechapel card', exact: true }).click()
  await search.fill('Whitechapel')
  await page.getByRole('option', { name: /Whitechapel/ }).first().click()
  await expect(page.getByRole('region', { name: 'Whitechapel timetable', exact: true })).toBeVisible()
})

test('National Rail and airport cards can be dismissed and restored', async ({ page }, info) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  const search = page.getByRole('searchbox')
  await search.fill('SRA')
  await page.getByRole('option').filter({ hasText: 'Stratford' }).first().click()
  const rail = page.getByRole('region', { name: 'National Rail at Stratford', exact: true })
  await expect(rail).toBeVisible()
  if (info.project.name === 'iphone-webkit') await rail.locator('summary').first().click()
  await expect(rail.getByRole('region', { name: 'Typical passenger demand' })).toBeVisible()
  await rail.getByRole('button', { name: 'Close Stratford National Rail card', exact: true }).click()
  await expect(rail.locator('details').first()).not.toBeVisible()
  await expect(search).toHaveValue('Stratford')
  await rail.getByRole('button', { name: 'Show Stratford National Rail card', exact: true }).click()
  await expect(rail.getByRole('combobox', { name: 'National Rail station' })).toHaveValue('stratford')
  await search.fill('LHR')
  await page.getByRole('option', { name: /Heathrow Airport/ }).first().click()
  const airport = page.locator('.edition-airport-card')
  await expect(airport.locator('.ms-airport-hero')).toBeVisible()
  await page.screenshot({ path: `/tmp/allchange-hero-dismiss/${info.project.name}-airport.png` })
  await airport.getByRole('button', { name: 'Close LHR card', exact: true }).click()
  await expect(airport.locator('.ms-airport-hero')).not.toBeVisible()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-selected-airport', 'heathrow')
  await airport.getByRole('button', { name: 'Show LHR card', exact: true }).click()
  await expect(airport.locator('.ms-airport-hero')).toBeVisible()
})

test('a dismissed partial rail card stays dismissed when its data arrives', async ({ page }, info) => {
  await page.route('**/all-change-national-rail-network-liverpool-street.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.getByRole('searchbox').fill('SRA')
  await page.getByRole('option').filter({ hasText: 'Stratford' }).first().click()
  const loading = page.getByRole('region', { name: 'National Rail at Stratford', exact: true })
  if (info.project.name === 'iphone-webkit') await loading.locator(':scope > details > summary').click()
  await expect(loading).toContainText('some National Rail services unavailable')
  await page.getByRole('button', { name: 'Close Stratford National Rail card', exact: true }).click()
  await expect(loading.getByRole('combobox', { name: 'National Rail station' })).not.toBeVisible()
  await page.getByRole('button', { name: 'Show Stratford National Rail card', exact: true }).click()
  await page.unroute('**/all-change-national-rail-network-liverpool-street.json')
  await loading.getByRole('button', { name: 'Retry National Rail board', exact: true }).click()
  await page.getByRole('button', { name: 'Close Stratford National Rail card', exact: true }).click()
  const ready = page.getByRole('region', { name: 'National Rail at Stratford', exact: true })
  await expect(ready).toHaveAttribute('data-hero-dismissed', 'true')
  await expect(ready.getByRole('button', { name: 'Show Stratford National Rail card', exact: true })).toBeVisible()
  await expect(ready).toContainText('National Rail calls loaded')
})
