import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('phone controls stay out of the map and remain reachable on short screens', async ({ page }, info) => {
  test.skip(info.project.name !== 'iphone-webkit')
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  const toggle = page.locator('#london-controls-toggle')
  const panel = page.locator('#london-controls-panel')
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(panel).not.toBeVisible()
  await expect(page.getByRole('searchbox')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion' }).click()
  // The signature transition is available without discovering the controls panel.
  const transition = page.locator('.london-spatial-cta')
  await expect(transition).toHaveText('↔Try diagram')
  await transition.click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-layout-mix', '1.000')
  await expect(transition).toHaveText('↔Back to geography')
  await transition.click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-layout-mix', '0.000')

  for (const viewport of [{ width: 390, height: 664 }, { width: 320, height: 568 }]) {
    await page.setViewportSize(viewport)
    await setMobileControls(page, true)
    await expect(page.getByRole('button', { name: 'Show National Rail', exact: true })).toBeVisible()
    const bounds = await panel.boundingBox()
    const timeline = await page.locator('.london-transport').boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width)
    expect(bounds!.y + bounds!.height).toBeLessThan(timeline!.y)
    await page.getByRole('button', { name: 'Vehicle labels auto' }).click()
    await expect(page.getByRole('button', { name: 'Vehicle labels on' })).toBeVisible()
    await page.getByRole('button', { name: 'Vehicle labels on' }).click()
    await page.getByRole('button', { name: 'Vehicle labels off' }).click()
    const targets = await panel.locator('button:visible').evaluateAll(buttons => buttons.map(button => button.getBoundingClientRect().height))
    expect(targets.every(height => height >= 44)).toBe(true)
    await page.keyboard.press('Escape')
    await expect(panel).not.toBeVisible()
    await expect(transition).toBeVisible()
    await expect(toggle).toBeFocused()
    await expect(page.getByRole('button', { name: 'Resume motion' })).toBeVisible()
  }

  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Tube · DLR', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Tube · DLR', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await setMobileControls(page, false)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Tube · DLR', exact: true }).click()
  await expect(page.locator('.london-experience')).not.toHaveClass(/has-selection/)
  await page.getByRole('searchbox').fill('Waterloo')
  await expect(panel).not.toBeVisible()
  await expect(page.getByRole('option').first()).toBeVisible()
  expect(await page.getByRole('searchbox').evaluate(input => getComputedStyle(input).fontSize)).toBe('16px')
  await page.getByRole('searchbox').press('Escape')
  await page.getByRole('button', { name: 'Enter limited chrome' }).click()
  await expect(toggle).not.toBeVisible()
  await expect(transition).not.toBeVisible()
  await page.getByRole('button', { name: 'Exit limited chrome' }).click()
  await expect(toggle).toBeVisible()
})

test('desktop retains the visible controls', async ({ page }, info) => {
  test.skip(info.project.name !== 'desktop-chromium')
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await expect(page.locator('#london-controls-toggle')).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Diagram layout' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Zoom in' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Tube · DLR', exact: true })).toBeVisible()
})
