import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('National Rail loads on demand and shares both timetable windows', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const requests: string[] = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion' }).click()
  expect(requests.some(url => url.includes('national-rail-network-paddington'))).toBe(false)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  const board = page.getByRole('region', { name: 'National Rail at Paddington' })
  await expect(board).toBeVisible()
  await setMobileControls(page, false)
  if (info.project.name === 'iphone-webkit') await board.locator(':scope > details > summary').click()
  await expect(board.locator('tbody tr:has(button)')).toHaveCount(4)
  await setMobileControls(page, true)
  await expect(page.getByRole('button', { name: 'Diagram layout' })).toBeDisabled()
  await expect(board).toContainText('Published times · not live')
  await setMobileControls(page, false)
  await board.getByRole('button', { name: 'Arrivals', exact: true }).click()
  await expect(board.getByRole('columnheader', { name: 'From', exact: true })).toBeVisible()
  await setMobileControls(page, false)
  await board.locator('tbody tr button').first().click()
  await setMobileControls(page, false)
  await board.getByRole('button', { name: 'Show movement' }).click()
  await expect(page.getByRole('button', { name: 'Resume motion' })).toBeVisible()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-study-window', 'morning')
  await page.screenshot({ path: `/tmp/allchange-national-rail/${info.project.name}.png` })
  const bounds = await board.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: '24-hour study' }).click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-study-window', 'day')
  await expect(board).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Hide National Rail', exact: true }).click()
  await expect(board).not.toBeVisible()
  await setMobileControls(page, true)
  await expect(page.getByRole('button', { name: 'Diagram layout' })).toBeEnabled()
  expect(requests.filter(url => url.includes('national-rail-network-paddington'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('National Rail handles failed loading and retries without breaking the base map', async ({ page }, info) => {
  await page.route('**/all-change-national-rail-network-paddington.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  await setMobileControls(page, false)
  const board = page.getByRole('region', { name: 'National Rail at Paddington', exact: true })
  if (info.project.name === 'iphone-webkit') await board.locator(':scope > details > summary').click()
  await expect(board).toContainText('some National Rail services unavailable')
  await expect(board.locator('tbody tr:has(button)')).toHaveCount(4)
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Hide National Rail', exact: true }).click()
  await page.unroute('**/all-change-national-rail-network-paddington.json')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  await expect(page.getByRole('region', { name: 'National Rail at Paddington' })).toBeVisible()
})

test('Paddington pulse automatically includes National Rail in its shared clock and flow lenses', async ({ page }, info) => {
  const errors: string[] = []
  const requests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion' }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  expect(requests.some(url => url.includes('national-rail-network-paddington'))).toBe(false)
  const picker = page.getByRole('combobox', { name: 'Pulse interchange' })
  await setMobileControls(page, false)
  await picker.selectOption('paddington')
  const experience = page.locator('.london-experience')
  await expect(page.locator('.london-pulse-rail')).toContainText('GWR')
  const morningCount = Number(await experience.getAttribute('data-pulse-national-rail-calls'))
  expect(morningCount).toBeGreaterThan(20)
  await expect(page.locator('.london-time-copy')).toContainText('07:45')
  await setMobileControls(page, true)
  await expect(page.getByRole('button', { name: 'Show National Rail', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await setMobileControls(page, true)
  const category = page.getByRole('button', { name: 'National Rail', exact: true })
  await category.click()
  await expect(category).toHaveAttribute('aria-pressed', 'true')
  await category.click()
  await setMobileControls(page, false)
  await page.getByRole('button', { name: 'radial movements', exact: true }).click()
  expect(Number(await experience.getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(0)
  await setMobileControls(page, false)
  await page.getByRole('button', { name: 'all movements', exact: true }).click()
  await expect(experience).toHaveAttribute('data-pulse-national-rail-calls', String(morningCount))
  await page.screenshot({ path: `/tmp/allchange-national-rail/pulse-${info.project.name}.png` })
  const search = await page.locator('.london-search').boundingBox()
  const status = await page.locator('.london-status-card').boundingBox()
  expect(status!.y).toBeGreaterThanOrEqual(search!.y + search!.height)
  await setMobileControls(page, false)
  await picker.selectOption('bank')
  await expect(experience).toHaveAttribute('data-pulse-national-rail-calls', '0')
  await expect(category).not.toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: '24-hour study', exact: true }).click()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  await setMobileControls(page, false)
  await picker.selectOption('paddington')
  await expect.poll(async () => Number(await experience.getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(morningCount)
  await expect(page.locator('.london-time-copy')).toContainText('07:45')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Exit interchange pulse', exact: true }).click()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  await expect(picker).toHaveValue('paddington')
  expect(requests.filter(url => url.includes('national-rail-network-paddington'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('Paddington pulse keeps TfL calls available while National Rail retries', async ({ page }) => {
  await page.route('**/all-change-national-rail-network-paddington.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  await setMobileControls(page, false)
  await page.getByRole('combobox', { name: 'Pulse interchange' }).selectOption('paddington')
  await expect(page.locator('.london-pulse-rail')).toContainText('National Rail unavailable')
  await setMobileControls(page, true)
  await expect(page.getByRole('button', { name: 'Tube · DLR', exact: true })).toBeVisible()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.unroute('**/all-change-national-rail-network-paddington.json')
  await setMobileControls(page, false)
  await page.getByRole('button', { name: 'Retry National Rail', exact: true }).click()
  await expect(page.locator('.london-pulse-rail')).toContainText('GWR')
})

test('Waterloo and Clapham pulses reuse their SWR corridor and preserve the clock', async ({ page }, info) => {
  const errors: string[] = [], requests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  const picker = page.getByRole('combobox', { name: 'Pulse interchange' })
  await setMobileControls(page, false)
  await picker.selectOption('waterloo')
  await expect(page.locator('.london-pulse-rail')).toContainText('SWR')
  const experience = page.locator('.london-experience')
  expect(Number(await experience.getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(20)
  await expect(page.locator('.london-time-copy')).toContainText('07:45')
  expect(requests.filter(url => url.includes('national-rail-network-waterloo'))).toHaveLength(1)
  expect(requests.filter(url => url.includes('national-rail-network-paddington'))).toHaveLength(0)
  await setMobileControls(page, false)
  await picker.selectOption('clapham-junction')
  expect(Number(await experience.getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(10)
  await setMobileControls(page, false)
  await page.getByRole('button', { name: 'radial movements', exact: true }).click()
  await expect(experience).toHaveAttribute('data-pulse-lens', 'radial')
  await page.screenshot({ path: `/tmp/allchange-waterloo/clapham-${info.project.name}.png` })
  await setMobileControls(page, false)
  await picker.selectOption('paddington')
  await expect(page.locator('.london-pulse-rail')).toContainText('GWR')
  await setMobileControls(page, false)
  await picker.selectOption('waterloo')
  await expect(page.locator('.london-pulse-rail')).toContainText('SWR')
  expect(requests.filter(url => url.includes('national-rail-network-waterloo'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('Kings Cross pulse loads its mainline corridor on demand and retains flow lenses', async ({ page }, info) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  expect(requests.some(url => url.includes('national-rail-'))).toBe(false)
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue('kings-cross')
  await expect(page.locator('.london-pulse-rail')).toContainText('LNER')
  const experience = page.locator('.london-experience')
  const count = Number(await experience.getAttribute('data-pulse-national-rail-calls'))
  expect(count).toBeGreaterThan(25)
  expect(requests.filter(url => url.includes('national-rail-network-kings-cross'))).toHaveLength(1)
  expect(requests.some(url => /national-rail-network-(paddington|waterloo)/.test(url))).toBe(false)
  await expect(page.locator('.london-time-copy')).toContainText('07:45')
  await setMobileControls(page, false)
  await page.getByRole('button', { name: 'radial movements', exact: true }).click()
  expect(Number(await experience.getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(20)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'National Rail', exact: true }).click()
  await setMobileControls(page, true)
  await expect(page.getByRole('button', { name: 'National Rail', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.screenshot({ path: `/tmp/allchange-kings-cross/pulse-${info.project.name}.png` })
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'National Rail', exact: true }).click()
  await setMobileControls(page, false)
  await page.getByRole('button', { name: 'all movements', exact: true }).click()
  await expect(experience).toHaveAttribute('data-pulse-national-rail-calls', String(count))
  await setMobileControls(page, false)
  await page.getByRole('combobox', { name: 'Pulse interchange' }).selectOption('bank')
  await expect(experience).toHaveAttribute('data-pulse-national-rail-calls', '0')
  await setMobileControls(page, false)
  await page.getByRole('combobox', { name: 'Pulse interchange' }).selectOption('kings-cross')
  await expect(experience).toHaveAttribute('data-pulse-national-rail-calls', String(count))
  expect(requests.filter(url => url.includes('national-rail-network-kings-cross'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('Kings Cross board shares the day clock, shows origins and opens its pulse', async ({ page }, info) => {
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  const paddington = page.getByRole('region', { name: 'National Rail at Paddington', exact: true })
  await expect(paddington).toBeVisible()
  await setMobileControls(page, false)
  if (info.project.name === 'iphone-webkit') await paddington.locator(':scope > details > summary').click()
  await setMobileControls(page, false)
  await page.getByRole('combobox', { name: 'National Rail station' }).selectOption('kings-cross')
  const board = page.getByRole('region', { name: 'National Rail at King’s Cross', exact: true })
  await expect(board.locator('tbody tr:has(button)')).toHaveCount(3)
  await expect(board).toContainText('Friday timetable')
  await setMobileControls(page, false)
  await board.getByRole('button', { name: 'Arrivals', exact: true }).click()
  await expect(board.getByRole('columnheader', { name: 'From', exact: true })).toBeVisible()
  await page.screenshot({ path: `/tmp/allchange-kings-cross/map-${info.project.name}.png`, animations: 'disabled' })
  const box = await board.boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(0)
  expect(box!.x + box!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: '24-hour study', exact: true }).click()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('0')
  await expect(board.locator('tbody tr td:first-child .ms-board-sr-only')).toHaveText(['00:08', '00:18', '00:24'])
  await setMobileControls(page, false)
  await board.locator('tbody tr button').first().click()
  await setMobileControls(page, false)
  await board.getByRole('button', { name: 'Show movement', exact: true }).click()
  await expect(page.locator('.london-time-copy')).toContainText('00:06')
  await setMobileControls(page, false)
  await board.locator(':scope > details > summary').click()
  await setMobileControls(page, false)
  await board.getByRole('button', { name: 'Open King’s Cross pulse', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue('kings-cross')
  expect(Number(await page.locator('.london-experience').getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(400)
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
})

test('Kings Cross pulse retains TfL and retries a failed rail download', async ({ page }) => {
  await page.route('**/all-change-national-rail-network-kings-cross.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  await expect(page.locator('.london-pulse-rail')).toContainText('National Rail unavailable')
  await setMobileControls(page, true)
  await expect(page.getByRole('button', { name: 'Tube · DLR', exact: true })).toBeVisible()
  await page.unroute('**/all-change-national-rail-network-kings-cross.json')
  await setMobileControls(page, false)
  await page.getByRole('button', { name: 'Retry National Rail', exact: true }).click()
  await expect(page.locator('.london-pulse-rail')).toContainText('LNER')
  expect(Number(await page.locator('.london-experience').getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(25)
})

test('SWR board selects movements and opens its respective pulse', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  const paddington = page.getByRole('region', { name: 'National Rail at Paddington', exact: true })
  await expect(paddington).toBeVisible()
  await setMobileControls(page, false)
  if (info.project.name === 'iphone-webkit') await paddington.locator(':scope > details > summary').click()
  await setMobileControls(page, false)
  await page.getByRole('combobox', { name: 'National Rail station' }).selectOption('waterloo')
  const waterloo = page.getByRole('region', { name: 'National Rail at Waterloo', exact: true })
  await expect(waterloo).toBeVisible()
  if (await waterloo.locator(':scope > details').getAttribute('open') === null && info.project.name === 'iphone-webkit') {
    // Switching while a corridor finishes loading can mount a fresh collapsed board.
    await setMobileControls(page, false)
    await waterloo.locator(':scope > details > summary').click()
  }
  await waterloo.getByRole('combobox', { name: 'Waterloo board line' }).selectOption('South Western Railway')
  await expect(waterloo.locator('tbody tr:has(button)')).toHaveCount(4)
  await expect(waterloo.locator('tbody tr:has(button)').first()).toContainText('South Western Railway')
  await setMobileControls(page, false)
  await waterloo.getByRole('button', { name: 'Arrivals', exact: true }).click()
  await setMobileControls(page, false)
  await waterloo.locator('tbody tr button').first().click()
  await setMobileControls(page, false)
  await waterloo.getByRole('button', { name: 'Show movement', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  await page.screenshot({ path: `/tmp/allchange-waterloo/map-${info.project.name}.png` })
  await setMobileControls(page, false)
  await waterloo.getByRole('button', { name: 'Show Waterloo National Rail card', exact: true }).click()
  await setMobileControls(page, false)
  await waterloo.getByRole('button', { name: 'Open Waterloo pulse', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue('waterloo')
  await expect(page.locator('.london-pulse-rail')).toContainText('SWR')
  expect(errors).toEqual([])
})

test('a failed SWR corridor keeps GWR available and retries independently', async ({ page }, info) => {
  await page.route('**/all-change-national-rail-network-waterloo.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  const paddington = page.getByRole('region', { name: 'National Rail at Paddington', exact: true })
  await expect(paddington).toBeVisible()
  await setMobileControls(page, false)
  if (info.project.name === 'iphone-webkit') await paddington.locator(':scope > details > summary').click()
  await paddington.getByRole('combobox', { name: 'Paddington board line' }).selectOption('GWR')
  await expect(paddington.locator('tbody tr:has(button)')).toHaveCount(4)
  await setMobileControls(page, false)
  await page.getByRole('combobox', { name: 'National Rail station' }).selectOption('waterloo')
  const placeholder = page.getByRole('region', { name: 'National Rail at Waterloo', exact: true })
  await expect(placeholder).toContainText('some National Rail services unavailable')
  await expect(placeholder.locator('tbody tr:has(button)')).toHaveCount(4)
  await page.unroute('**/all-change-national-rail-network-waterloo.json')
  await setMobileControls(page, false)
  await placeholder.getByRole('button', { name: 'Retry National Rail board' }).click()
  await expect(placeholder.getByRole('combobox', { name: 'Waterloo board line' }).locator('option')).toContainText(['South Western Railway'])
  await expect(page.getByRole('region', { name: 'National Rail at Waterloo', exact: true })).toBeVisible()
})

test('expanded gateways and branch stations open their own rail pulses', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  await setMobileControls(page, false)
  const board = page.locator('.london-national-rail-board')
  await expect(board.locator(':scope > details > summary')).toBeVisible()
  if (info.project.name === 'iphone-webkit') await board.locator(':scope > details > summary').click()
  const station = page.getByRole('combobox', { name: 'National Rail station' })
  await expect(station.locator('option')).toHaveCount(301)
  for (const id of ['victoria', 'london-bridge', 'charing-cross', 'cannon-street', 'liverpool-street', 'euston', 'marylebone', 'fenchurch-street', 'st-pancras', 'st-pancras-thameslink', 'moorgate', 'rail:HXX', 'rail:CSS', 'rail:HYS', 'rail:WAE', 'rail:BCZ', 'rail:LEB']) {
    await station.selectOption(id)
    await expect.poll(() => board.locator('tbody tr:has(button)').count()).toBeGreaterThan(0)
    const name = await station.locator('option:checked').textContent()
    await board.getByRole('button', { name: `Open ${name} pulse`, exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue(id)
    await expect.poll(async () => Number(await page.locator('.london-experience').getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(0)
    await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
    await setMobileControls(page, true)
    await page.getByRole('button', { name: 'Exit interchange pulse', exact: true }).click()
    await setMobileControls(page, false)
    if (info.project.name === 'iphone-webkit') await board.locator(':scope > details > summary').click()
  }
  await page.screenshot({ path: `/tmp/allchange-rail-complete/branches-${info.project.name}.png` })
  expect(errors).toEqual([])
})

test('rail search finds station codes and services while rail is hidden', async ({ page }, info) => {
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  const search = page.locator('.london-search input')
  await search.fill('LBG')
  await page.getByRole('option').filter({ hasText: 'NATIONAL RAIL · LBG' }).click()
  const board = page.getByRole('region', { name: 'National Rail at London Bridge', exact: true })
  await expect(board).toBeVisible()
  if (info.project.name === 'iphone-webkit') await board.locator(':scope > details > summary').click()
  await expect(board).toContainText('Thameslink')
  await expect(board).toContainText('Southern')
  await expect(board).toContainText('Southeastern')
  await search.fill('Chiltern')
  await page.getByRole('option').filter({ hasText: 'NATIONAL RAIL' }).first().click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-study-window', 'day')
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  await expect(page.locator('.london-national-rail-selection')).toBeVisible()
})
