import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('rail loads on demand, opens movement and finds a hidden-layer service across timetable windows', async ({ page }, info) => {
  const requests: string[] = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  expect(requests.some(url => url.includes('national-rail-network-'))).toBe(false)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  await setMobileControls(page, false)
  const board = page.getByRole('region', { name: 'National Rail at Paddington', exact: true })
  await expect(board).toBeVisible()
  if (info.project.name === 'iphone-webkit') await board.locator(':scope > details > summary').click()
  await board.getByRole('combobox', { name: 'Paddington board line' }).selectOption('GWR')
  await board.locator('tbody tr button').first().click()
  await board.getByRole('button', { name: 'Show movement', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  const bounds = (await board.boundingBox())!
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Hide National Rail', exact: true }).click()
  await page.getByRole('searchbox').fill('Chiltern')
  await page.getByRole('option').filter({ hasText: 'NATIONAL RAIL' }).first().click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-study-window', 'day')
  const railCard = page.locator('.london-national-rail-board')
  if (await railCard.locator(':scope > details').getAttribute('open') === null) await railCard.locator(':scope > details > summary').click()
  await expect(page.locator('.london-national-rail-selection')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
})

test('service pulse mounts lazily and shares selected station and clock with the map', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await setMobileControls(page, true)
  const response = page.waitForResponse(response => response.url().includes('/assets/HubPulseScene-'))
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  expect((await response).ok()).toBe(true)
  await expect(page.locator('.scene canvas')).toBeVisible()
  await expect(page.locator('.london-pulse-rail')).toContainText('LNER')
  await setMobileControls(page, false)
  await page.getByRole('button', { name: 'radial movements', exact: true }).click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-pulse-lens', 'radial')
  await page.getByRole('combobox', { name: 'Pulse interchange' }).selectOption('waterloo')
  await expect(page.locator('.london-pulse-rail')).toContainText('SWR')
  await expect(page.locator('.london-transport input[type="range"]')).toHaveValue('27900')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  const search = (await page.locator('.london-search').boundingBox())!
  const card = (await page.locator('.london-status-card').boundingBox())!
  expect(card.y).toBeGreaterThanOrEqual(search.y + search.height)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Exit interchange pulse', exact: true }).click()
  await expect(page.locator('.london-experience')).not.toHaveClass(/is-pulse-study/)
  await expect(page.locator('.scene canvas')).toBeVisible()
})
