import { expect, test } from '@playwright/test'

test('National Rail loads on demand and shares both timetable windows', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const requests: string[] = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion' }).click()
  expect(requests.some(url => url.includes('national-rail-paddington'))).toBe(false)
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  const board = page.getByRole('region', { name: 'National Rail at Paddington' })
  await expect(board).toBeVisible()
  if (info.project.name === 'iphone-webkit') await board.locator('summary').click()
  await expect(board.locator('li')).toHaveCount(3)
  await expect(page.getByRole('button', { name: 'Diagram layout' })).toBeDisabled()
  await expect(board).toContainText('Published times · not live')
  await board.getByRole('button', { name: 'Arrivals', exact: true }).click()
  await expect(board.locator('li').first()).toContainText('Via Reading')
  await board.locator('li button').first().click()
  await board.getByRole('button', { name: 'Show movement' }).click()
  await expect(page.getByRole('button', { name: 'Resume motion' })).toBeVisible()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-study-window', 'morning')
  await page.screenshot({ path: `/tmp/allchange-national-rail/${info.project.name}.png` })
  const bounds = await board.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.getByRole('button', { name: '24-hour study' }).click()
  await expect(page.locator('.london-experience')).toHaveAttribute('data-study-window', 'day')
  await expect(board).toBeVisible()
  await page.getByRole('button', { name: 'Hide National Rail', exact: true }).click()
  await expect(board).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Diagram layout' })).toBeEnabled()
  expect(requests.filter(url => url.includes('national-rail-paddington'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('National Rail handles failed loading and retries without breaking the base map', async ({ page }) => {
  await page.route('**/all-change-national-rail-paddington.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'National Rail unavailable' })).toBeVisible()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Hide National Rail', exact: true }).click()
  await page.unroute('**/all-change-national-rail-paddington.json')
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  await expect(page.getByRole('region', { name: 'National Rail at Paddington' })).toBeVisible()
})

test('Paddington pulse automatically includes National Rail in its shared clock and flow lenses', async ({ page }, info) => {
  const errors: string[] = []
  const requests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion' }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  expect(requests.some(url => url.includes('national-rail-paddington'))).toBe(false)
  const picker = page.getByRole('combobox', { name: 'Pulse interchange' })
  await picker.selectOption('paddington')
  const experience = page.locator('.london-experience')
  await expect(page.locator('.london-pulse-rail')).toContainText('GWR')
  const morningCount = Number(await experience.getAttribute('data-pulse-national-rail-calls'))
  expect(morningCount).toBeGreaterThan(20)
  await expect(page.locator('.london-time-copy')).toContainText('07:45')
  await expect(page.getByRole('button', { name: 'Show National Rail', exact: true })).toHaveAttribute('aria-pressed', 'false')
  const category = page.getByRole('button', { name: 'National Rail', exact: true })
  await category.click()
  await expect(category).toHaveAttribute('aria-pressed', 'true')
  await category.click()
  await page.getByRole('button', { name: 'radial movements', exact: true }).click()
  expect(Number(await experience.getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'all movements', exact: true }).click()
  await expect(experience).toHaveAttribute('data-pulse-national-rail-calls', String(morningCount))
  await page.screenshot({ path: `/tmp/allchange-national-rail/pulse-${info.project.name}.png` })
  const search = await page.locator('.london-search').boundingBox()
  const status = await page.locator('.london-status-card').boundingBox()
  expect(status!.y).toBeGreaterThanOrEqual(search!.y + search!.height)
  await picker.selectOption('waterloo')
  await expect(experience).toHaveAttribute('data-pulse-national-rail-calls', '0')
  await expect(category).not.toBeVisible()
  await page.getByRole('button', { name: '24-hour study', exact: true }).click()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  await picker.selectOption('paddington')
  await expect.poll(async () => Number(await experience.getAttribute('data-pulse-national-rail-calls'))).toBeGreaterThan(morningCount)
  await expect(page.locator('.london-time-copy')).toContainText('07:45')
  await page.getByRole('button', { name: 'Exit interchange pulse', exact: true }).click()
  await page.getByRole('button', { name: 'Show National Rail', exact: true }).click()
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  await expect(picker).toHaveValue('paddington')
  expect(requests.filter(url => url.includes('national-rail-paddington'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('Paddington pulse keeps TfL calls available while National Rail retries', async ({ page }) => {
  await page.route('**/all-change-national-rail-paddington.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await page.getByRole('button', { name: 'Interchange pulse', exact: true }).click()
  await page.getByRole('combobox', { name: 'Pulse interchange' }).selectOption('paddington')
  await expect(page.locator('.london-pulse-rail')).toContainText('National Rail unavailable')
  await expect(page.getByRole('button', { name: 'Tube · DLR', exact: true })).toBeVisible()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.unroute('**/all-change-national-rail-paddington.json')
  await page.getByRole('button', { name: 'Retry National Rail', exact: true }).click()
  await expect(page.locator('.london-pulse-rail')).toContainText('GWR')
})
