import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('night preset keeps Friday morning bounded and exposes gaps without inventing closure', async ({ page }, info) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  expect(requests.some(url => /LondonNightStudy|all-change-night-study/.test(url))).toBe(false)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'After midnight study', exact: true }).click()
  await setMobileControls(page, false)
  const experience = page.locator('.london-experience'), clock = page.locator('.london-transport input[type="range"]')
  await expect(experience).toHaveAttribute('data-night-study', 'true')
  await expect(experience).toHaveAttribute('data-spatial-layout', 'geographic')
  await expect(clock).toHaveAttribute('min', '0')
  await expect(clock).toHaveAttribute('max', '18000')
  await expect(clock).toHaveValue('1800')
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  await expect(experience).toHaveAttribute('data-bus-loading', 'false')
  const overview = page.getByRole('region', { name: 'After midnight', exact: true })
  await expect(overview).toContainText('Thursday night into Friday morning')
  await expect(overview).toContainText('Thursday rail carry-in is included')
  await overview.getByRole('button', { name: '02:30', exact: true }).click()
  await expect(clock).toHaveValue('9000')
  await expect(overview).toContainText('567 buses on 123 routes')
  await overview.getByRole('button', { name: /^Bank City interchange/ }).click()
  const bank = page.getByRole('region', { name: 'Bank night departures', exact: true })
  await expect(page.locator('.london-national-rail-board')).toHaveCount(0)
  await expect(page.locator('.london-passenger-demand')).toContainText('Thursday tail · typical Tue–Thu')
  await expect(bank).toContainText('05:30')
  await expect(bank).toContainText('in 180 min')
  await expect(bank).toContainText('beyond this night view')
  await expect(bank).toContainText('does not prove no service ran')
  await expect(bank.getByRole('button', { name: 'Go to next departure' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Close Bank card', exact: true }).click()
  await expect(clock).toHaveValue('9000')
  await page.getByRole('button', { name: 'Show Bank card', exact: true }).click()
  await expect(bank).toContainText('05:30')
  await bank.scrollIntoViewIfNeeded()
  expect(await bank.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: `/tmp/allchange-night/${info.project.name}.png`, animations: 'disabled' })
  await page.getByRole('button', { name: 'Clear search and selection', exact: true }).click()
  await overview.getByRole('button', { name: '00:30', exact: true }).click()
  await overview.getByRole('button', { name: /^Waterloo Mainline terminal/ }).click()
  const waterloo = page.getByRole('region', { name: 'Waterloo night departures', exact: true })
  await expect(waterloo).toContainText('00:30')
  await waterloo.getByRole('button', { name: 'Go to next departure' }).click()
  await expect(clock).toHaveValue('1800')
  await clock.fill('18000')
  await expect(waterloo).toContainText('Night view ends at 05:00')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: '24-hour study', exact: true }).click()
  await expect(experience).toHaveAttribute('data-night-study', 'false')
  await expect(clock).toHaveAttribute('max', '86400')
  expect(requests.filter(url => url.endsWith('/all-change-night-study.json'))).toHaveLength(1)
  expect(errors).toEqual([])
})

test('night context retries independently of the map and remains optional outside night mode', async ({ page }, info) => {
  await page.route('**/all-change-night-study.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'After midnight study', exact: true }).click()
  await setMobileControls(page, false)
  const overview = page.locator('.london-status-card .london-night')
  await expect(overview).toContainText('Night context unavailable')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.unroute('**/all-change-night-study.json')
  await overview.getByRole('button', { name: 'Retry night context' }).click()
  await expect(overview).toContainText('Thursday night into Friday morning')
  await overview.getByRole('button', { name: /^Upminster Outer London/ }).click()
  await expect(page.getByRole('region', { name: 'Upminster night departures', exact: true })).toContainText('Rail only; buses are separate')
  await page.getByRole('searchbox').fill('WAT')
  await page.getByRole('option').filter({ hasText: 'NATIONAL RAIL · WAT' }).click()
  const rail = page.getByRole('region', { name: 'National Rail at Waterloo', exact: true })
  if (info.project.name === 'iphone-webkit') await rail.locator(':scope > details > summary').click()
  await expect(rail.getByRole('region', { name: 'Waterloo night departures', exact: true })).toContainText('00:30')
  await page.getByRole('button', { name: 'Close Waterloo National Rail card', exact: true }).click()
  await page.getByRole('button', { name: 'Show Waterloo National Rail card', exact: true }).click()
  await expect(rail).toHaveAttribute('data-hero-dismissed', 'false')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Morning study', exact: true }).click()
  await setMobileControls(page, false)
  await expect(page.locator('.london-experience')).toHaveAttribute('data-night-study', 'false')
  await expect(page.locator('.london-night')).toHaveCount(0)
  await expect(page.locator('.london-transport input[type="range"]')).toHaveAttribute('min', '24300')
})
