import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('night preset loads the map and departure card, seeks its clock and returns to the full day', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'After midnight study', exact: true }).click()
  await setMobileControls(page, false)
  const experience = page.locator('.london-experience'), clock = page.locator('.london-transport input[type="range"]')
  await expect(experience).toHaveAttribute('data-night-study', 'true')
  await expect(experience).toHaveAttribute('data-bus-loading', 'false')
  await expect(clock).toHaveValue('1800')
  await expect(clock).toHaveAttribute('max', '18000')
  const overview = page.getByRole('region', { name: 'After midnight', exact: true })
  await overview.getByRole('button', { name: '02:30', exact: true }).click()
  await expect(clock).toHaveValue('9000')
  await overview.getByRole('button', { name: /^Bank City interchange/ }).click()
  const bank = page.getByRole('region', { name: 'Bank night departures', exact: true })
  await expect(bank).toContainText('beyond this night view')
  await expect(page.locator('.london-passenger-demand')).toContainText('Thursday tail')
  await bank.scrollIntoViewIfNeeded()
  expect(await bank.evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await setMobileControls(page, true)
  await page.getByRole('button', { name: '24-hour study', exact: true }).click()
  await expect(experience).toHaveAttribute('data-night-study', 'false')
  await expect(clock).toHaveAttribute('max', '86400')
})
