import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('Bank demand loads on selection, follows the clock and stays available in its pulse', async ({ page }, info) => {
  const requests: string[] = [], errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  const search = page.getByRole('searchbox')
  expect(requests.filter(url => /passenger-demand|LondonPassengerDemand/.test(url))).toEqual([])
  await search.fill('Bank')
  await page.getByRole('option', { name: /Bank/ }).first().click()
  const card = page.getByRole('region', { name: 'Typical passenger demand' })
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await expect(card).toContainText('Bank and Monument')
  await expect(card).toContainText('Typical Friday · autumn 2025')
  await expect(card.getByRole('button', { name: /Entering/ })).toContainText('≈254')
  await expect(card.getByRole('button', { name: /Leaving/ })).toContainText('≈1,360')
  await expect(card.getByTestId('passenger-marker')).toHaveAttribute('data-interval', '11')
  await card.getByRole('button', { name: /Changing/ }).click()
  await expect(card.getByRole('img')).toHaveAccessibleName(/Changing daily profile. Peak 17:30–17:45/)
  const bounds = await card.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.screenshot({ path: `/tmp/allchange-passenger-demand/${info.project.name}-bank.png`, animations: 'disabled' })
  await page.locator('.london-transport input[type="range"]').fill('28800')
  await expect(card.getByTestId('passenger-marker')).toHaveAttribute('data-interval', '12')
  await page.getByRole('button', { name: 'Open Bank pulse', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue('bank')
  await expect(card).toContainText('Bank and Monument')
  await page.getByRole('combobox', { name: 'Pulse interchange' }).selectOption('stratford')
  await expect(card).toContainText('Stratford · NUMBAT source area')
  await expect(card.getByRole('button', { name: /Changing/ })).toHaveAttribute('aria-pressed', 'true')
  expect(requests.filter(url => url.endsWith('/stations/BNKu.json'))).toHaveLength(1)
  await page.screenshot({ path: `/tmp/allchange-passenger-demand/${info.project.name}-pulse.png`, animations: 'disabled' })
  expect(errors).toEqual([])
})

test('passenger data retries and never wraps the Saturday tail into Friday morning', async ({ page }) => {
  await page.route('**/all-change-passenger-demand/stations/BNKu.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.getByRole('searchbox').fill('Bank')
  await page.getByRole('option', { name: /Bank/ }).first().click()
  const card = page.getByRole('region', { name: 'Typical passenger demand' })
  await expect(card).toContainText('Passenger data unavailable')
  await page.unroute('**/all-change-passenger-demand/stations/BNKu.json')
  await card.getByRole('button', { name: 'Retry passenger data', exact: true }).click()
  await expect(card).toContainText('Bank and Monument')
  await setMobileControls(page, true)
  await page.getByRole('button', { name: '24-hour study', exact: true }).click()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await setMobileControls(page, false)
  await page.getByRole('searchbox').fill('Bank')
  await page.getByRole('option', { name: /Bank/ }).first().click()
  await page.locator('.london-transport input[type="range"]').fill('3600')
  await expect(card).toContainText('No matching interval in this study day')
  await expect(card.getByRole('button', { name: /Entering/ })).toContainText('—')
  await expect(card.getByTestId('passenger-marker')).toHaveCount(0)
  await page.locator('.london-transport input[type="range"]').fill('63000')
  await expect(card).toContainText('17:30–17:45 · estimated people')
  await expect(card.getByTestId('passenger-marker')).toHaveAttribute('data-interval', '50')
})

test('Stratford National Rail hero shares the demand profile with its pulse', async ({ page }, info) => {
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.getByRole('searchbox').fill('SRA')
  await page.getByRole('option').filter({ hasText: 'Stratford' }).first().click()
  const rail = page.getByRole('region', { name: 'National Rail at Stratford', exact: true })
  await expect(rail).toBeVisible()
  if (info.project.name === 'iphone-webkit') await rail.locator('summary').first().click()
  const card = rail.getByRole('region', { name: 'Typical passenger demand' })
  await expect(card).toContainText('Stratford · NUMBAT source area')
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await expect(card.getByRole('button', { name: /Entering/ })).toContainText('≈1,042')
  await page.screenshot({ path: `/tmp/allchange-passenger-demand/${info.project.name}-rail.png`, animations: 'disabled' })
  await rail.getByRole('button', { name: 'Open Stratford pulse', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue('stratford')
  await expect(page.getByRole('region', { name: 'Typical passenger demand' })).toContainText('Stratford · NUMBAT source area')
})
