import { expect, test } from '@playwright/test'
import bank from '../fixtures/passenger-demand/stations/BNKu.json' with { type: 'json' }

test('passenger pulse compares morning/evening with separate flows and a shared clock', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await page.getByRole('searchbox').fill('Bank')
  await page.getByRole('option', { name: /Bank/ }).first().click()
  await page.getByRole('button', { name: 'Explore passenger flow', exact: true }).click()
  const pulse = page.getByRole('region', { name: 'Passenger flow study', exact: true })
  await expect(pulse).toBeVisible()
  await expect(page.getByRole('button', { name: 'Show Bank card', exact: true })).toBeVisible()
  await expect(pulse.locator('[data-flow="exits"]')).toHaveAttribute('data-value', '1359.927')
  await expect(pulse).toContainText('Typical Friday · autumn 2025')
  await expect(pulse).toContainText('not tracked paths or train occupancy')
  await pulse.getByRole('button', { name: '17:30 evening', exact: true }).click()
  await expect(page.locator('.london-transport input[type="range"]')).toHaveValue('63000')
  await expect(pulse.locator('[data-flow="entries"]')).toHaveAttribute('data-value', String(bank.station.entries[50]))
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  await page.screenshot({ path: `/tmp/allchange-passenger-pulse/${info.project.name}-evening.png`, animations: 'disabled' })
  const firstDot = pulse.locator('[data-flow="entries"] circle').first()
  const position = await firstDot.getAttribute('cx')
  await page.getByRole('button', { name: 'Resume motion', exact: true }).click()
  await expect(firstDot).not.toHaveAttribute('cx', position!)
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await pulse.getByRole('combobox', { name: 'Passenger pulse station' }).selectOption('stratford')
  await expect(pulse.getByRole('img')).toHaveAccessibleName(/Stratford/)
  await page.getByRole('button', { name: 'Train services pulse', exact: true }).click()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue('stratford')
  await page.getByRole('button', { name: 'Passenger flow pulse', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('3600')
  await expect(pulse.locator('[data-flow="entries"]')).toHaveAttribute('data-value', 'unavailable')
  await expect(pulse.locator('circle')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('passenger pulse respects reduced motion and recovers failed profile downloads', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/all-change-passenger-demand/stations/SFDu.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.getByRole('searchbox').fill('Bank')
  await page.getByRole('option', { name: /Bank/ }).first().click()
  await page.getByRole('button', { name: 'Explore passenger flow', exact: true }).click()
  const pulse = page.getByRole('region', { name: 'Passenger flow study', exact: true })
  await expect(pulse).toHaveAttribute('data-reduced-motion', 'true')
  await page.locator('.london-transport input[type="range"]').fill('27900')
  const dot = pulse.locator('[data-flow="entries"] circle').first()
  const x = await dot.getAttribute('cx')
  await page.locator('.london-transport input[type="range"]').fill('27920')
  await expect(dot).toHaveAttribute('cx', x!)
  await pulse.getByRole('combobox', { name: 'Passenger pulse station' }).selectOption('stratford')
  await expect(pulse).toContainText('Passenger data unavailable')
  await expect(pulse.locator('circle')).toHaveCount(0)
  await page.unroute('**/all-change-passenger-demand/stations/SFDu.json')
  await pulse.getByRole('button', { name: 'Retry passenger pulse' }).click()
  await expect(pulse.locator('[data-flow="interchanges"]')).toHaveAttribute('data-value', '3226.197')
})

test('wider hero coverage keeps source areas separate and unsupported metrics absent', async ({ page }) => {
  const requests: string[] = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  expect(requests.some(url => url.includes('all-change-passenger-demand'))).toBe(false)
  const search = page.getByRole('searchbox')
  await search.fill('Whitechapel')
  await page.getByRole('option', { name: /Whitechapel/ }).first().click()
  const card = page.getByRole('region', { name: 'Typical passenger demand' }).first()
  await expect(card).toContainText('Whitechapel · NUMBAT source area')
  expect(requests.some(url => url.endsWith('/stations/WCLu.json'))).toBe(true)
  expect(requests.filter(url => /passenger-demand\/stations\//.test(url))).toHaveLength(1)
  await search.fill('Canary Wharf')
  await page.getByRole('option', { name: /Canary Wharf/ }).first().click()
  const areas = card.getByRole('combobox', { name: 'Passenger source area' })
  await expect(areas.locator('option')).toHaveCount(3)
  await areas.selectOption('CAWd')
  await expect(card).toContainText('Canary Wharf DLR · NUMBAT source area')
  await search.fill('CLJ')
  await page.getByRole('option').filter({ hasText: 'Clapham Junction' }).first().click()
  const rail = page.getByRole('region', { name: 'National Rail at Clapham Junction', exact: true })
  await expect(rail).toBeVisible()
  if (await rail.locator('details').first().getAttribute('open') === null) await rail.locator('summary').first().click()
  await expect(rail).toContainText('Changing unavailable: ambiguous duplicate')
  await expect(rail.getByRole('button', { name: /^Changing/ })).toHaveCount(0)
  await search.fill('Addington Village')
  await page.getByRole('option', { name: /Addington Village/ }).first().click()
  await expect(page.getByRole('region', { name: 'Addington Village timetable', exact: true })).toBeVisible()
  await expect(page.locator('.london-status-card .london-passenger-demand')).toHaveCount(0)
  expect(requests.some(url => url.endsWith('/stations/ADVt.json'))).toBe(false)
})
