import { expect, test } from '@playwright/test'
import bank from '../fixtures/passenger-demand/stations/BNKu.json' with { type: 'json' }

test('passenger pulse compares morning/evening with separate flows and a shared clock', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  await page.getByRole('searchbox').fill('Bank')
  await page.getByRole('option', { name: /Bank/ }).first().click()
  await page.getByRole('button', { name: 'Explore passenger flow', exact: true }).click()
  const pulse = page.getByRole('region', { name: 'Passenger flow study', exact: true })
  await expect(pulse).toBeVisible()
  await expect(page.getByRole('button', { name: 'Show Bank card', exact: true })).toBeVisible()
  await expect(pulse.locator('[data-flow="exits"]')).toHaveAttribute('data-value', '1359.927')
  await expect(pulse).toContainText('Typical Friday · autumn 2025')
  await expect(pulse).toContainText('not tracked paths or train occupancy')
  await pulse.getByRole('button', { name: '17:30 evening', exact: true }).click()
  await expect(page.locator('.london-transport input[type="range"]')).toHaveValue('63000')
  await expect(pulse.locator('[data-flow="entries"]')).toHaveAttribute('data-value', String(bank.station.entries[50]))
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  const firstDot = pulse.locator('[data-flow="entries"] circle').first()
  const position = await firstDot.getAttribute('cx')
  await page.getByRole('button', { name: 'Resume motion', exact: true }).click()
  await expect(firstDot).not.toHaveAttribute('cx', position!)
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await pulse.getByRole('combobox', { name: 'Passenger pulse station' }).selectOption('stratford')
  await expect(pulse.getByRole('img')).toHaveAccessibleName(/Stratford/)
  await page.getByRole('button', { name: 'Train services pulse', exact: true }).click()
  await expect(page.locator('.scene canvas')).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Pulse interchange' })).toHaveValue('stratford')
  await page.getByRole('button', { name: 'Passenger flow pulse', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('3600')
  await expect(pulse.locator('[data-flow="entries"]')).toHaveAttribute('data-value', '10.509')
  await expect(pulse).toContainText('Thursday tail · typical Tue–Thu')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(pulse).toHaveAttribute('data-reduced-motion', 'true')
  await page.locator('.london-transport input[type="range"]').fill('27900')
  const dot = pulse.locator('[data-flow="entries"] circle').first()
  const x = await dot.getAttribute('cx')
  await page.locator('.london-transport input[type="range"]').fill('27920')
  await expect(dot).toHaveAttribute('cx', x!)
  expect(errors).toEqual([])
})
