import { expect, test } from '@playwright/test'
import { setMobileControls } from './mobile-controls.ts'

test('station hero board filters lines, selects a service and follows the study clock', async ({ page }, info) => {
  const errors: string[] = [], requests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => requests.push(request.url()))
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  expect(requests.some(url => url.includes('LondonStationDepartures'))).toBe(false)
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.locator('.london-transport input[type="range"]').fill('27900')
  const search = page.getByRole('searchbox')
  await search.fill('Whitechapel')
  await page.getByRole('option', { name: /Whitechapel/ }).first().click()
  const board = page.getByRole('region', { name: 'Whitechapel timetable', exact: true })
  await expect(board.locator('tbody tr')).toHaveCount(4)
  await expect(board).toContainText('2026-09-04 · 07:45–08:45')
  await expect(board).toContainText('Published times · not live')
  const filter = board.getByRole('combobox', { name: 'Whitechapel board line' })
  const options = await filter.locator('option').allTextContents()
  expect(options.length).toBeGreaterThan(2)
  await filter.selectOption({ label: options[1] })
  await expect(board.locator('tbody tr td:last-child .ms-board-sr-only')).toHaveText(Array(4).fill(options[1]))
  await board.getByRole('button', { name: 'Arrivals', exact: true }).click()
  await expect(board.getByRole('columnheader', { name: 'From', exact: true })).toBeVisible()
  await board.locator('tbody tr button').first().click()
  await expect(board.locator('.london-station-board-selection')).toBeVisible()
  await expect(board.locator('.ms-flap__drum').first()).toHaveCSS('visibility', 'hidden')
  const card = page.locator('.has-station-board')
  const bounds = await card.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width)
  await page.screenshot({ path: `/tmp/allchange-station-board/${info.project.name}.png`, animations: 'disabled' })
  await board.getByRole('button', { name: 'Show movement', exact: true }).click()
  await expect(board).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Resume motion', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})

test('station board respects reduced motion and preserves selection across layouts', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.getByRole('searchbox').fill('Whitechapel')
  await page.getByRole('option', { name: /Whitechapel/ }).first().click()
  const board = page.getByRole('region', { name: 'Whitechapel timetable', exact: true })
  await expect(board.locator('.ms-flap__face').first()).toHaveCSS('animation-name', 'none')
  await board.locator('tbody tr button').first().click()
  const selection = await board.locator('.london-station-board-selection').textContent()
  await setMobileControls(page, true)
  await page.getByRole('button', { name: 'Diagram layout', exact: true }).click()
  await setMobileControls(page, false)
  await expect(board.locator('.london-station-board-selection')).toHaveText(selection!)
  await expect(board.locator('tbody tr button[aria-pressed="true"]')).toHaveCount(1)
})

test('station board clips to loaded chunks and recovers a failed day download', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.scene canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await page.route('**/all-change-day-chunks/06-08.json', route => route.fulfill({ status: 503, body: 'Unavailable' }))
  await setMobileControls(page, true)
  await page.getByRole('button', { name: '24-hour study', exact: true }).click()
  await page.getByRole('button', { name: 'Pause motion', exact: true }).click()
  await setMobileControls(page, false)
  await page.getByRole('searchbox').fill('Whitechapel')
  await page.getByRole('option', { name: /Whitechapel/ }).first().click()
  const board = page.getByRole('region', { name: 'Whitechapel timetable', exact: true })
  await expect(board.getByRole('status').filter({ hasText: 'Timetable download failed' })).toBeVisible()
  await page.unroute('**/all-change-day-chunks/06-08.json')
  await board.getByRole('button', { name: 'Retry board data', exact: true }).click()
  await expect(board.locator('tbody tr')).toHaveCount(4)
  await expect(board.locator('.london-station-board-window')).toContainText('08:00')
  await page.locator('.london-transport input[type="range"]').fill('86400')
  await expect(board.getByRole('status').filter({ hasText: 'Outside study window.' })).toBeAttached()
  await expect(board.locator('tbody tr button')).toHaveCount(0)
})
